### ISSUE TITLE
[Bug] The 'send' button color does not change.

### ISSUE THREAD

**Issue by dmotts** [dmotts/customer-support-bot#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The 'send' button and message box top border in the chat widget does not change to the primary theme color.

### Expected behavior

The 'send' button should have the same background color as primary theme color settings for this plugin 

### Add ScreenShots

![IMG_20241006_105236](https://github.com/user-attachments/assets/93264fde-6077-444c-9bc6-89938358bff1)
![Screenshot_20241006-103447](https://github.com/user-attachments/assets/12903ecc-fe9a-4650-af05-099021a8b2cf)

### Record

- [X] I have read the Contributing Guidelines
- [X] I have starred the repository

**Comment by AmanWebDev2** [comment]
@dmotts can you assign this to me, i have done with the coding part, will raise a PR within a minutes😁

**Comment by dmotts** [comment]
@AmanWebDev2 Sure! Thanks for your contribution! 🙌
