### ISSUE TITLE
[Bug] Logo is not displaying on chat window

### ISSUE THREAD

**Issue by dmotts** [dmotts/customer-support-bot#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There was a logo on the top left corner of the chat window but it no longer displays.

### Expected behavior

There should be a logo showing on the top left corner of the chat window.

### Add Screenshots

![IMG_20241015_234320](https://github.com/user-attachments/assets/f1599599-1ca0-4e0b-b414-5d217abe0217)

### On which device are you experiencing this bug?

Android, iPhone, Linux, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I have starred the repository

**Comment by Badra00** [comment]
Hey
Could you assign this issue to me?

**Comment by Daksh-134** [comment]
Hi @dmotts  ,pls assign this issue to me if it is not completed

**Comment by dmotts** [comment]
Hey @Daksh-134, nice to meet you! Thank you for taking an interest in this project! 🙌🥳

Have fun, and if you don't mind me asking. How did you hear about this project? #32

**Comment by Daksh-134** [comment]
I found this on https://goodfirstissues.com/

**Comment by dmotts** [comment]
Thank you for your feedback, @Daksh-134! I really appreciate it!

If you have any questions, feel free to ask. 🖐️🗣️

**Comment by dmotts** [comment]
Thank you for your contribution as well @Daksh-134!

**Comment by dmotts** [comment]
How's it going @Daksh-134?

**Comment by AmanWebDev2** [comment]
@dmotts can you assign this to me, I have already fixed it

**Comment by dmotts** [comment]
> @dmotts can you assign this to me, I have already fixed it

Great! @AmanWebDev2 I want to give @Daksh-134 a chance to respond first, and after sometime, I'll switch the assignment on to you. 

Thank you for your contributions! 🙂

**Comment by AmanWebDev2** [comment]
No issues, is it okay if I raise a PR for this?

**Comment by Daksh-134** [comment]
> > @dmotts can you assign this to me, I have already fixed it
> 
> Great! @AmanWebDev2 I want to give @Daksh-134 a chance to respond first, and after sometime, I'll switch the assignment on to you.
> 
> Thank you for your contributions! 🙂

Sorry I was busy with some other stuff,you can unassign me from this issue.

**Comment by dmotts** [comment]
@Daksh-134 That's okay. Do you still want to try?

**Comment by Daksh-134** [comment]
> @Daksh-134 That's okay. Do you still want to try?

No you can assign it to someone else.

**Comment by dmotts** [comment]
@Daksh-134 Thanks for trying. I appreciate your time! 😀

**Comment by dmotts** [comment]
It's all yours @AmanWebDev2!
