### ISSUE TITLE
[Bug] Multiple assistant message

### ISSUE THREAD

**Issue by AmanWebDev2** [dmotts/customer-support-bot#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Clicking on the chat widget and closing it multiple times may cause the assistant text to appear multiple times

### Expected behavior

When I click on the widget the welcome / assitant text should be appear one time

### Add Screenshots

https://github.com/user-attachments/assets/c5d69839-e011-49d9-b0d1-dc980ac3a6a8

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I have starred the repository

**Comment by AmanWebDev2** [comment]
@dmotts can you assign this to me please?

**Comment by dmotts** [comment]
@AmanWebDev2 Sure! Get it! 😜
