### ISSUE TITLE
[Feature Request] Add text color to settings

### ISSUE THREAD

**Issue by dmotts** [dmotts/customer-support-bot#47]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

There needs to be a setting that allows you to change the text color.

### Use Case

Similar to the theme settings. The text should be able to change through a color picker option.

### Benefits

- Improved UI/UX

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I have starred the repository

**Comment by AmanWebDev2** [comment]
@dmotts Can you assign this to me?

**Comment by dmotts** [comment]
You are on 🔥🔥🔥 @AmanWebDev2!
