### ISSUE TITLE
[Feature Request] Increase size of logo

### ISSUE THREAD

**Issue by dmotts** [dmotts/customer-support-bot#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Increase the size of the logo of the avatar. It should be relatively the same size of the avatar.

### Use Case

User's will be able to clearly see the logo in the top left corner.

### Benefits

- Improved UI/UX

### Add Screenshots

![IMG_20241020_095143](https://github.com/user-attachments/assets/8da74eae-a278-4521-8d28-2cfffa78913a)

### Priority

Low

### Record

- [X] I have read the Contributing Guidelines
- [X] I have starred the repository

**Comment by Shivakarthikeya23** [comment]
I can fix this issue , please assign it to me

**Comment by dmotts** [comment]
Sure @Shivakarthikeya23! Thanks for being a part of this project!

**Comment by Shivakarthikeya23** [comment]
Thanks for assigning , I have created a PR for the respective change.
https://github.com/dmotts/customer-support-bot/pull/50
Please have a look.

Thanks
